baseURL = "http://example.com/"
languageCode = "es-es"
title = "Nombre de mi empresa"
theme = "minimal"

[params]
    author = "Calin Tataru"
    description = "<div style='text-align:center;'><img src='/image/logo.png' height='100px'></img></br></br>Frase descriptiva de su empresa </div>"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "linen"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    copyright = "Servicio provisto por <a href='http://www.leantech.cl/' target='_blank'>Leantech.</a>"


[[menu.main]]
    url = "/"
    name = "Inicio"
    weight = 1
    title = "Inicio"

[[menu.main]]
    url = "/quienes-somos/"
    name = "Quienes Somos"
    weight = 2

[[menu.main]]
    url = "/servicios/"
    name = "Servicios"
    weight = 3

[[menu.main]]
    url = "/contacto/"
    name = "Contáctanos"
    weight = 4

[[menu.main]]
    url = "/ubicacion/"
    name = "Ubicación"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4
